Websocket name from session
gatling/gatling pull request #4035
Opened 2021-01-05 13:58 UTC by jklingelAvid

Added support for websocket names based on Session contents
Added missing charset param in PebbleBenchmark.scala

2021-01-12 12:42 UTC, slandelle requested changes
Thanks for contributing!

Please address my comments.

FYI, we're currently updating our CLA process, so I'll ping you when we're ready so we can proceed with it and then merge.

2021-01-12 12:42 UTC, slandelle commented on gatling-benchmarks/src/main/scala/io/gatling/core/session/pebble/PebbleBenchmark.scala
> +  private val LoopPebbleBody = PebbleStringBody(resourceAsString("sample-peeble2.json", charset), charset)
Oops! No idea why this didn't show up on CI.

2021-01-12 12:42 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/WsAction.scala
> +      .flatMap(name => {
Please remove extra parens:

```scala
.flatMap { name =>

}
```

2021-01-12 12:42 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/WsConnect.scala
> +import io.gatling.core.session._
Weird. You're importing `session._` while the line below imports `session.{ Expression, Session }`. If you need something else, please remove the second line that becomes useless.

2021-01-13 08:46 UTC, jklingelAvid commented
Thanks a lot for the review. I changed it according to your suggestion.

2021-01-13 10:48 UTC, slandelle commented
Thanks! Could you please sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw)?

Also, could you please fix the commit history and squash into a single one on top of master? If you really can't do that, I'll take care of it.

Cheers

2021-01-13 13:02 UTC, closed without merging

2021-01-13 13:29 UTC, jklingelAvid commented
@slandelle I messed up with the squash & rebase. I'm now creating another pull request with a clean branch. Sorry for the inconvenience