Add support EL for ws.checkTextMessage
gatling/gatling pull request #4136
Opened 2021-09-08 14:29 UTC by Amerousful

2021-09-08 14:36 UTC, slandelle requested changes
Sorry, but your approach is wrong. The Expression should be resolved in the Action, not in the FSM.

2021-09-08 14:54 UTC, Amerousful commented
Hmm ... Apparently I went the wrong way.
This should be done in WsSend, WsClose, etc., right?

2021-09-08 14:59 UTC, slandelle commented
Indeed. Meaning you would have to duplicate the WsFrameCheckSequenceBuilder, WsTextFrameCheck and WsBinaryFrameCheck classes :(

Could you please explain your use case?

2021-09-08 15:11 UTC, Amerousful commented
My use case is that I add a unique ID to the name of each request: build number + launch uniqueness. I add this through the EL. The need for this is that I then compare the metrics for different launches.

The problem is that checkTextMessage is written to logs / metrics and I cannot change its name through EL

2021-09-20 11:10 UTC, Amerousful commented
Stéphane, hello again!
I followed your advice and moved resolving to Actions.

But it seems to me that my decision is still "dirty"...
1) I don't know how to handle Failure correctly - https://github.com/gatling/gatling/pull/4136/files#diff-9b0ea77b65d56feb4d08135246b7be1851ca4d9fcd61a88d5a104246e3478572R43
2) Сonfuses with cast (asInstanceOf) - https://github.com/gatling/gatling/pull/4136/files#diff-9b0ea77b65d56feb4d08135246b7be1851ca4d9fcd61a88d5a104246e3478572R33

If you can give a hint or advice - I will be very grateful.

2021-10-05 06:59 UTC, slandelle commented
> My use case is that I add a unique ID to the name of each request: build number + launch uniqueness. I add this through the EL. The need for this is that I then compare the metrics for different launches.

With unique IDs in the check name, you're going to flood the reporting engine and make the reports unusable. I guess you expect the parse the log file yourself, which I definitely don't recommend as this file is an internal, subject to change anytime.

2021-10-05 07:06 UTC, slandelle requested changes

2021-10-05 07:06 UTC, slandelle commented on gatling-http-java/src/main/java/io/gatling/http/javaapi/Ws.java
> +      return new WsFrameCheck.Text(io.gatling.http.Predef.ws().checkTextMessage(toStringExpression(name)));
Please also add the overload that takes a Java function.

2021-10-05 07:06 UTC, slandelle commented on gatling-http-java/src/main/java/io/gatling/http/javaapi/Ws.java
> +      return new WsFrameCheck.Binary(io.gatling.http.Predef.ws().checkBinaryMessage(toStringExpression(name)));
Please also add the overload that takes a Java function.

2021-10-05 07:06 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/check/ws/WsFrameCheck.scala
> +  final case class Binary(checkName: Expression[String], matchConditions: List[WsCheck.Binary], checks: List[WsCheck.Binary], isSilent: Boolean, name: String)
I don't like it. I'd rather have 2 sets of types: one for the DSL with the Expression and one for runtime with the resolved value.

2021-10-05 07:06 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/check/ws/WsFrameCheck.scala
> +      extends WsFrameCheck {
same as above

2021-10-05 07:06 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/WsFrameCheckSequenceBuilder.scala
> +  private def resolveCheckName[T <: WsFrameCheck](checks: List[WsFrameCheck], session: Session): List[WsFrameCheck] = {
First, I don't like it. I'd rather have 2 sets of types: one for the DSL with the Expression and one for runtime with the resolved value.

Then, you don't properly handle failures. What you must do is a recursive resolution. See here for an example https://github.com/gatling/gatling/blob/15664aa2fbfbf4ac55190eb83115e219a777d529/gatling-core/src/main/scala/io/gatling/core/session/package.scala#L58-L79

2021-11-03 21:22 UTC, slandelle requested changes

2021-11-03 21:22 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/Ws.scala
> +  def checkTextMessage(name: String): WsFrameCheck.Text = checkTextMessage(itemToElString(name))
Please remove. You don't need to overload: a String parameter would implicitly be converted into an Expression[String]. That's how **all** the other methods in Gatling's DSL work.

2021-11-03 21:22 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/Ws.scala
> +  def checkBinaryMessage(name: String): WsFrameCheck.Binary = checkBinaryMessage(itemToElString(name))
Please remove, same as above.

2021-11-03 21:22 UTC, slandelle commented on gatling-core/src/main/scala/io/gatling/core/session/package.scala
> +  def itemToElString(item: String): Session => Validation[String] = {
useless, see below, please revert

2021-11-03 21:22 UTC, slandelle commented on gatling-core/src/main/scala/io/gatling/core/session/package.scala
> +  def itemToEl(item: Any): Session => Validation[Any] = {
useless, see below, please revert

2021-11-03 21:22 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/WsFrameCheckSequenceBuilder.scala
> +  def resolve[T <: WsFrameCheck](builders: List[WsFrameCheckSequenceBuilder[T]], session: Session): Validation[List[WsFrameCheckSequence[T]]] = {
Please remove those useless extra curly braces.

2021-11-03 21:22 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/action/ws/WsFrameCheckSequenceBuilder.scala
> +    def resolveCheckName[C <: WsFrameCheck](entries: Iterator[C], session: Session, acc: List[C]): Validation[List[C]] = {
You mustn't use an Iterator for that, that's not the Scala way.
You must pattern match the List, see https://github.com/gatling/gatling/blob/main/gatling-core/src/main/scala/io/gatling/core/check/Check.scala#L47-L61 for an example

2021-11-03 21:22 UTC, slandelle commented on gatling-http/src/main/scala/io/gatling/http/check/ws/WsFrameCheck.scala
> +  final case class Binary(checkName: Expression[String], matchConditions: List[WsCheck.Binary], checks: List[WsCheck.Binary], isSilent: Boolean, name: String)
> how similar logic was implemented for queryParamMap / queryParamSeq and decided to try it the same way. I found this to be a simpler solution...

Where is that?
`queryParam` uses 2 different sets:
* `io.gatling.http.request.builder.HttpParam` with unresolved Expressions
* `io.gatling.http.client.Param` for resolved Strings

See https://github.com/gatling/gatling/blob/main/gatling-http/src/main/scala/io/gatling/http/request/builder/package.scala#L62

2021-11-05 16:53 UTC, slandelle commented
@Amerousful sorry I took so long to review. Do you think you'll be able to tackle my comments in the next days. We're drawing near the 3.7.0 release (probably the week after next week).

2021-11-18 22:03 UTC, slandelle commented
As the release is drawing near, I cherry-picked your commit, fixed rebasing and did a little clean up.
See https://github.com/gatling/gatling/commit/46eb42ec22e075f6a8e7b484f368a0ce79ce9b68

Thanks a lot for contributing!

2021-11-18 22:03 UTC, closed without merging

2021-11-19 10:08 UTC, Amerousful commented
@slandelle 
Wow, that's cool!
Big thanks for your time to review the pull request. 
I will take time to check the clean-up in detail so I'll be able to write more beautiful code in the future.