Tcp writeback pressure
gatling/gatling pull request #4202
Opened 2022-02-01 16:21 UTC by vJoeyz

**Contents**
This pull request contains the implementation of a revised `TcpSender` used for sending statistics to Graphite. This revised version implements NACK-based write back-pressure with suspending, providing more reliability and data conservation when sending statistics.

**Rationale**
In the current version of the TcpSender,  when a response isn't received within the `WritePeriod` (1 second by default) from Gatling's config (due to a slow db connection, resource problems etc.), the request is rejected, but the data is never buffered or resent. Furthermore, if this happens more than _5_ times (as specified in the hardcoded `maxRetries`), the writing to Graphite halts completely, never to be resumed.

I have tested this implementation in my load tests and it fully resolves all issues I had with the current TcpSender when recording large amounts of data to a database.

**Credits**
This implementation was heavily inspired by Akka's [sample implementation](https://github.com/akka/akka/blob/v2.6.18/akka-docs/src/test/scala/docs/io/EchoServer.scala).

2022-02-01 16:59 UTC, slandelle requested changes
Thanks fro contributing!

Could you please:
* run `compile` to format your code and organize your imports
* address comments
* sign our CLA: https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw/edit

Thanks!

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +          case Failure(_) => goto(BufferOverflow) using NoData
case _

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +  }
single instruction => useless {}

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +  }
single instruction => useless {}

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +    require(data.storage.nonEmpty, s"Storage was empty at ack $ack")
What happens if this throws?

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +      goto(Running) using ConnectedData(connection, failures, 0, Vector.empty[ByteString], 0L, false, 0)
Vector.empty[ByteString] => Nil

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSenderFSM.scala
> +private[sender] final case class ConnectedData(connection: ActorRef, retry: Retry, storageOffset: Int, storage: Vector[ByteString], stored: Long, suspended: Boolean, nack: Int) extends TcpSenderData
Why Vector?

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +        case Failure(_) => goto(BufferOverflow) using NoData
case _ =>

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +        case Success(data) => stay() using data
Rename so you're not  shadowing the `data` reference.

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +      logger.info(s"Failed to write to Graphite server located at: $remote, buffering...")
Shouldn't it be a warning?

2022-02-01 16:59 UTC, slandelle commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +    var peerClosed = false
Those should be in `ConnectedData`.

2022-02-04 14:22 UTC, vJoeyz commented on gatling-graphite/src/main/scala/io/gatling/graphite/sender/TcpSender.scala
> +    require(data.storage.nonEmpty, s"Storage was empty at ack $ack")
the actor will be restarted

2022-02-04 15:05 UTC, slandelle commented
@vJoeyz Have you seen all the `^M` chars in your last commits? eg https://github.com/gatling/gatling/pull/4202/files#diff-696b3ab9a3d6b03bfb45bb037cc20cb0ac1e81f9070f05116d63a99c5e796419R23

2022-02-04 15:17 UTC, vJoeyz commented
> @vJoeyz Have you seen all the `^M` chars in your last commits? eg https://github.com/gatling/gatling/pull/4202/files#diff-696b3ab9a3d6b03bfb45bb037cc20cb0ac1e81f9070f05116d63a99c5e796419R23

They appeared after running `compile`

2022-02-04 15:21 UTC, slandelle commented
> They appeared after running compile

???
What's your OS? Windows?

2022-02-04 15:23 UTC, vJoeyz commented
> > They appeared after running compile
> 
> ??? What's your OS? Windows?

Yes.

2022-02-04 17:14 UTC, slandelle commented
Do you use something like `git config core.autocrlf`?

2022-02-05 15:46 UTC, vJoeyz commented
> Do you use something like `git config core.autocrlf`?

Not that I'm aware of, no. Anyways, I've removed them. :)

2022-02-07 08:24 UTC, slandelle commented
> Anyways, I've removed them. :)

Yeah, but your code is not properly formatted. It would if you were using `compile` to trigger scalafmt. As is, your PR won't pass our CI. We're going to investigate our settings for Windows but I'm not sure the issue is there.

Also, you commit history is broken because it doesn't only have your commits rebased on top of our main branch.

2022-02-08 17:44 UTC, slandelle commented
@vJoeyz We'll release 3.7.5 next week. By then, do you thing you'll be able to fix your commit history and your formatting?

2022-02-11 13:37 UTC, slandelle commented
I tried to fix formatting and wartremover on your branch, but still, `TcpSenderSpec` doesn't pass:

```
[info] - should go to the Running state and send metrics if it could connect without issues *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected Write(ByteString(102, 111, 111, 32, 49, 32, 49, 10),NoAck(null)), found Write(ByteString(102, 111, 111, 32, 49, 32, 49, 10),Ack(0))
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at io.gatling.graphite.sender.TcpSenderSpec.$anonfun$new$3(TcpSenderSpec.scala:64)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
14:30:06.218 [pool-1-thread-1-ScalaTest-running-TcpSenderSpec] WARN io.gatling.graphite.sender.TcpSenderSpec$TcpSenderNoIo - Disconnected from Graphite server located at: 0.0.0.0/0.0.0.0:9999, retrying...
[info] - should retry to connected until the retry limit has been exceeded to finally stop *** FAILED ***
[info]   FlushingBuffer was not equal to Running (TcpSenderSpec.scala:80)
```

2022-09-05 10:03 UTC, biski commented
I've tested this fix and it works in my case. Before fix integration with graphite used to stop after ~24h. Please merge it to stable, thanks :)

2022-09-05 10:17 UTC, slandelle commented
@biski There's no way to merge this work as is:
* code formatting violation everywhere, while one just has to run compile/Test:compile to format automatically
* merge conflict

Contributions welcome

2022-10-12 09:21 UTC, vJoeyz commented
> @biski There's no way to merge this work as is:
> 
> * code formatting violation everywhere, while one just has to run compile/Test:compile to format automatically
> * merge conflict
> 
> Contributions welcome

Sorry for my late reply, the past half year my health got it in way suddenly. I'll try to fix it up this week. :)

2022-10-12 10:34 UTC, slandelle commented
@vJoeyz Oh, sorry for you! I hope you're doing well now.
No worries, take you time. I haven't closed to PR for inactivity because I believe it has value. I've tried to rebase myself but had limited time for it and didn't manage to succeed.

2023-01-03 09:17 UTC, closed without merging

2023-01-03 09:18 UTC, slandelle commented
Closing as idle for too long and can't be merged.