Changed 'Gatling User Group' (name and link) to 'Gatling Community'.
gatling/gatling pull request #4310
Opened 2022-08-08 21:31 UTC by gemiusz

Changes made on all findings except [GatlingHomePage.html ](gatling-core/src/test/resources/GatlingHomePage.html)
I think this html need full refactor.

2022-08-08 22:03 UTC, slandelle requested changes
Thanks!

Could you please replace "Gatling Community" with "Gatling Community Forum"?

2022-08-08 22:33 UTC, gemiusz commented
> replace "Gatling Community" with "Gatling Community Forum"

Yes of course. 
Changes applied.

2022-08-09 06:06 UTC, slandelle approved these changes

2022-08-12 07:25 UTC, slandelle commented
Cherry-picked, thanks a lot!

2022-08-12 07:25 UTC, closed without merging